FROM node:20.17-alpine3.20

WORKDIR /app

RUN npm install -g corepack@latest

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY turbo.json ./
COPY pnpm-lock.yaml ./

COPY apps/admin ./apps/admin

COPY packages ./packages

RUN pnpm install --frozen-lockfile
RUN pnpm turbo run build --filter=admin

CMD ["pnpm","run","start-admin-app"] 