FROM node:20.17-alpine3.20

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY turbo.json ./
COPY pnpm-lock.yaml* ./

COPY apps/client ./apps/client

COPY packages ./packages

CMD ["pnpm","run","start-client-app"] 