name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "20"

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build the Turbo Repo
      run: pnpm run build

    - name: Build and Push Docker Images
      run: |
        # Define image names
        DOCKER_IMAGES=("client" "admin" "server")
        DOCKERFILES=("./docker/DockerFile.client" "./docker/DockerFile.admin" "./docker/DockerFile.server")

        for i in "${!DOCKER_IMAGES[@]}"; do
          IMAGE_NAME="adisolanki24/library-manager-${DOCKER_IMAGES[i]}"
          DOCKERFILE_PATH="${DOCKERFILES[i]}"

          echo "Building and pushing $IMAGE_NAME using $DOCKERFILE_PATH..."

          # Build and push Docker image
          docker build -t $IMAGE_NAME:latest -f $DOCKERFILE_PATH .
          docker push $IMAGE_NAME:latest

          # Verify pushed image
          docker pull $IMAGE_NAME:latest
        done

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # admin app deploy
          sudo docker pull adisolanki24/library-manager-admin:latest
          sudo docker stop library-manager-admin || true
          sudo docker rm library-manager-admin || true

          sudo docker image prune -f

          sudo docker run -d --restart=always --name library-manager-admin -p 3001:3001 \
          -e NODE_ENV="${{ secrets.NODE_ENV }}" \
          -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
          adisolanki24/library-manager-admin:latest

          # client app deploy
          sudo docker pull adisolanki24/library-manager-client:latest
          sudo docker stop library-manager-client || true
          sudo docker rm library-manager-client || true

          sudo docker image prune -f

          sudo docker run -d --restart=always --name library-manager-client -p 3000:3000 \
          -e NODE_ENV="${{ secrets.NODE_ENV }}" \
          -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
          adisolanki24/library-manager-client:latest

          # server app deploy
          sudo docker pull adisolanki24/library-manager-server:latest
          sudo docker stop library-manager-server || true
          sudo docker rm library-manager-server || true

          sudo docker image prune -f

          sudo docker run -d --restart=always --name library-manager-server -p 4000:4000 \
          -e NODE_ENV="${{ secrets.NODE_ENV }}" \
          -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
          -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
          -e AWS_ACCESS_KEY="${{ secrets.AWS_ACCESS_KEY }}" \
          -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -e AWS_REGION="${{ secrets.AWS_REGION }}" \
          -e FROM_NAME="Aditya Solanki" \
          -e FROM_EMAIL="aditya2ss283@gmail.com" \
          -e PORT=4000 \
          -e API_BASE_URL="http://localhost:4000" \